
package com.walid.gcd.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GCDServiceIMpl", targetNamespace = "http://gcd.walid.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GCDServiceIMpl {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gcd", targetNamespace = "http://gcd.walid.com/", className = "com.walid.gcd.client.Gcd")
    @ResponseWrapper(localName = "gcdResponse", targetNamespace = "http://gcd.walid.com/", className = "com.walid.gcd.client.GcdResponse")
    @Action(input = "http://gcd.walid.com/GCDServiceIMpl/gcdRequest", output = "http://gcd.walid.com/GCDServiceIMpl/gcdResponse")
    public int gcd();

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listGCDs", targetNamespace = "http://gcd.walid.com/", className = "com.walid.gcd.client.ListGCDs")
    @ResponseWrapper(localName = "listGCDsResponse", targetNamespace = "http://gcd.walid.com/", className = "com.walid.gcd.client.ListGCDsResponse")
    @Action(input = "http://gcd.walid.com/GCDServiceIMpl/listGCDsRequest", output = "http://gcd.walid.com/GCDServiceIMpl/listGCDsResponse")
    public List<Integer> listGCDs();

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sumGCDs", targetNamespace = "http://gcd.walid.com/", className = "com.walid.gcd.client.SumGCDs")
    @ResponseWrapper(localName = "sumGCDsResponse", targetNamespace = "http://gcd.walid.com/", className = "com.walid.gcd.client.SumGCDsResponse")
    @Action(input = "http://gcd.walid.com/GCDServiceIMpl/sumGCDsRequest", output = "http://gcd.walid.com/GCDServiceIMpl/sumGCDsResponse")
    public int sumGCDs();

}
